-- First, remove the table if it exists
drop table if exists customers;

-- Create the table anew
create table bookmarks(
    id INTEGER PRIMARY KEY GENERATED BY default AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL
);

--insert some test data
--Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values 
('Youtube', 'https://www.youtube.com', 'A website with tons of videos', 4),
('Google', 'https://www.google.com', 'The most popular search engine ever.', 5),
('Facebook', 'https://www.facebook.com', 'A social media website developed by Mark Zuckerberg', 4),
('Riot Games', 'https://www.riotgames.com/en', 'My favorite online video game ever.', 5),
('Amazon', 'https://www.amazon.com', 'The reason why brick and mortar stores will perish', 3),
('HomeByMe', 'https://www.home.by.me/en/', 'A site where you can design homes in virtual reality', 4),
('MTG Arena', 'https://www.magic.wizards.com/en/mtgarena', 'Wizards of the Coast official MTG Arena site', 4),
('Thinkful', 'https://www.thinkful.com', 'A website you can get a new job in 6 months', 4),
('Yahoo', 'https://www.yahoo.com', 'A website with the best sport fantasy options', 4),
('First Republic', 'https://www.firstrepublic.com', 'A bank website with the best customer service rating', 4)